version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lid
    image: registry.seacotec.com/lid:1.0.9
    restart: unless-stopped
    ports:
      - "4242:80"


#    api:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      container_name: lid
#      image: dtuncbilek/lid:1.0.8
#      restart: unless-stopped
#      ports:
#        - "4242:80"

# first use this...
# docker compose build
# docker push registry.seacotec.com/lid:1.0.9


# docker build --platform linux/amd64 -t dtuncbilek/lid:1.0.9 .
# docker push dtuncbilek/lid:1.0.9
