version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lid
    image: dtuncbilek/lid:1.0.0
    restart: unless-stopped
    ports:
      - "4242:80"


# build app
# docker compose build
# docker push dtuncbilek/lid:1.0.0
